shared:
  s3_access_key_id:     <%= ENV.fetch("S3_ACCESS_KEY_ID") if [:s3, :s3_multipart].include?(Rails.configuration.upload_server) %>
  s3_secret_access_key: <%= ENV.fetch("S3_SECRET_ACCESS_KEY") if [:s3, :s3_multipart].include?(Rails.configuration.upload_server) %>
  s3_region:            <%= ENV.fetch("S3_REGION") if [:s3, :s3_multipart].include?(Rails.configuration.upload_server) %>
  s3_bucket:            <%= ENV.fetch("S3_BUCKET") if [:s3, :s3_multipart].include?(Rails.configuration.upload_server) %>
  secret_key_base: 29aac4f296435c948bbf287456d2214f65f2d9e78285017e9118c113a6b177ae9a990ff5729208b25fceedddca71439bcefd2babc70ee4792938b79192d0647b
